# fly.toml app configuration file generated for change-my-life on 2024-11-29T12:35:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'change-my-life'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthcheck'

[[vm]]
  size = 'shared-cpu-1x'

[scale]
  count = 1
