[package]
name = "webserver"
version = "0.1.1-dev"
edition = "2021"
author = "JongBum Park"

[dependencies]
actix-web = { version = "4" }
#openssl = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
