[package]
name = "webserver"
version = "0.1.1-dev"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
actix-cors = "0.7.0"
actix-files = "0.6"
